# Generated by Django 3.1.4 on 2020-12-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='session',
            new_name='session_admitted',
        ),
    ]
