# Generated by Django 3.1.4 on 2020-12-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20201230_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
