# Generated by Django 3.1.4 on 2020-12-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='session',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(max_length=25),
        ),
    ]
