# Generated by Django 3.1.4 on 2021-01-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201231_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
