# Generated by Django 3.1.4 on 2020-12-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post Categories'},
        ),
    ]
